### ISSUE TITLE
v2.0.0 published on NPM?

### ISSUE THREAD

**Issue by deadratfink** [75lb/walk-back#1]
Hi Lloyd,

We've got some problems with the jsdoc-to-markdown library which references your lib in v2.0.0 (resolved by using '^') as transitive dependency (i.e. [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/v1.3.6/package.json)@1.3.6 -> [dmd](https://github.com/jsdoc2md/dmd/blob/v1.4.0/package.json)@1.4.0 -> walk-back@2.0.0). You have a npm badge which shows 2.0.0 but when you go to your [npm published site](https://www.npmjs.com/package/walk-back) there is still v1.1.1 provided as latest and using `npm install package-json-to-readme` fails:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: walk-back@'>=2.0.0 <3.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.1","1.0.0","1.0.1","1.1.0","1.1.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'dmd'
```

Pls could you check if walk-back is published properly on npmjs.org?

Thx and best regards 
Jens

**Comment by deadratfink** [comment]
Hmm, looks like this could be caused by our Sinopia server which cannot resolve this for unknown reasons. I changed the repo to https://registry.npmjs.org/ and a simple `npm install jsdoc-to-markdown` works now.

**Comment by 75lb** [comment]
walk-back v2 is definitely published to npm.. let me know if you figure it out..

**Comment by 75lb** [comment]
walk-back v2 is a dep of dmd, which is building/testing fine https://travis-ci.org/jsdoc2md/dmd.

**Comment by deadratfink** [comment]
Thx for rapid reply. Yes, will investigate the prob on our site and give you info, as said I can get it when I change the repo to npmjs.org (we use internal repo which uses npmjs.org as fallback, but for some reasons that one cannot resolve the v2.0.0). Will give you a note after some investigation. Sorry for inconvenience, ...but any idea why your npm badge seems to be correct (v2.0.0) but the npm site says that 1.1.1 is the latest?

**Comment by 75lb** [comment]
I noticed that too. I think the npm website has failed to refresh. If you
run 'npm view walk-back' you can see the data is correct.

**Comment by 75lb** [comment]
i just bumped the walk-back version to 2.0.1, to see if it forced the npm website to update - which it has.

**Comment by deadratfink** [comment]
Good to see :-)

I could fix the internal Sinopia issue by deleting the cached folder of walk-back and a subsequent `npm install walk-back@2.0.1` recreated a new cached folder. After that I called `npm install walk-back@2.0.0` and this also showed up in cached folder. Now everything works as expected. :-) 

Unfortunately, I could not retrace why Sinopia got that hick-up :-(

Thx for support!

Best regards
Jens

**Comment by 75lb** [comment]
i see - it sounds like a one-off glitch.. glad it’s working, now.. npm can be problematic sometimes, although i think it’s better now than it used to be!
